### ISSUE TITLE
SEB requires SHA-512 algorithm from 30.09.2023

### ISSUE THREAD

**Issue by lemmevMerada** [KonektOU/woocommerce-estonian-banklinks#24]
SEB requires all requests to use SHA-2 encryption (SHA-512) from 30. septembril 2023. Do you have any plans to update the SEB banklink in the plugin?
Here are the new technical requirements from the bank: https://www.seb.ee/sites/default/files/tac/pangalingi_tehniline_spec_EST.pdf

**Comment by RistoNiinemets** [comment]
Fixed in version 1.6
